name: "Validate a newly submitted schema issue"
description: "Validates action submissions via the issue template."
author: "bapo2"

inputs:
  issue_body:
    description: "The full-text body of the issue."
    required: true
  issue_labels:
    description: "The labels currently applied to the issue."
    required: true

outputs:
  issue_body:
    description: "The new body of the issue to replace the old one."
  issue_labels:
    description: "The labels to apply to the issue (comma-separated)."
  issue_comment:
    description: "A comment to post on the issue regarding the validation results."

runs:
  using: "docker"
  image: "Dockerfile"