name: "Add all open approved schemas to repo"
description: "Update the schema directory in the repo's README with the latest approved schemas."
author: "bapo2"

inputs:
  repo_path:
    description: "The path of this repo in the form 'owner/repo'."
    required: true
  issue_list:
    description: "A comma-separated list of issue numbers to update."
    required: true
  GITHUB_TOKEN:
    description: "The GitHub token for authentication."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"