# Imports
import os, re, json, unicodedata
from git import Repo, Git
from github import Github

# Generates a new schema entry for the README
def new_readme_entry(info, schema):
    format = info["format"].lower()
    return f"""
<!-- START_SCHEMA: "{info['title']}" -->
<tr><td><details><summary><b>{info['title']}</b> - {info['shortdesc']}</summary><p><ul>
<li><b>Author:</b> <a href="https://github.com/{info['author']}">{info['author']}</a></li>
<li><b>Schema format:</b> {format.upper()}</li>
<li><b>Authentication type:</b> {info['auth']}</li></ul></p>
<p><b>Description:</b><br><i>{info['desc']}</i></p>
<p><b>Import URL:</b><br>```{format}\nhttps://raw.githubusercontent.com/bapo2/gpt-actions/main/schemas/{info['folder_title']}/schema.{format}\n```
</p><p><b>Schema:</b>```{format}\n{schema}\n```</p></details></td></tr>
<!-- END_SCHEMA: "{info['title']}" -->
"""

# Slugifies a title so that it can be used as a directory name
def slugify(title):
    title = unicodedata.normalize('NFKD', title).encode('ascii', 'ignore').decode('ascii')
    return re.sub(r'[^\w\s-]', '', title.lower()).strip('-_').replace(' ', '-')

# Updates the README with the new schema directory
def update_readme(readme_path, directory, schemas_count):
    with open(readme_path, 'r') as f: readme_text = f.read()
    badge_pattern = r'https://img.shields.io/badge/(\d+)%20actions%20contributed'
    updated_readme = re.sub(badge_pattern, f'https://img.shields.io/badge/{schemas_count}%20actions%20contributed', readme_text)
    split_readme = updated_readme.split('<!-- START_SCHEMA_DIRECTORY -->')
    return split_readme[0] + "<!-- START_SCHEMA_DIRECTORY -->" + directory + "\n<!-- END_SCHEMA_DIRECTORY -->" + split_readme[1].split('<!-- END_SCHEMA_DIRECTORY -->')[1]

# The main function
def run():
    # Environment variables and setup
    token, repo_path = os.environ['GITHUB_TOKEN'], os.environ['INPUT_REPO_PATH']
    issue_numbers = os.environ['INPUT_ISSUE_LIST'].replace('"','').replace('#','').split(',')
    repo = Repo.clone_from(f"https://{token}@github.com/{repo_path}.git", 'repo')
    git = Git('repo')
    git.config('credential.helper', f'!echo password={token};')

    # Get issues and extract information
    g_repo = Github(token).get_repo(repo_path)
    issues_info = []
    pattern = r"### 📂 Name\s*\n*(.*?)\n*?\s*### 📰 Short Description\s*\n*(.*?)\n*?\s*### 📜 Format\s*\n*(.*?)\n*?\s*### 📋 Schema\s*\n*```(?:json|yaml)\n([\s\S]*?)\n```(?:\n*?)\s*### 🔑 Authentication\s*\n*(.*?)\n*?\s*### 📝 Description\s*\n*([\s\S]*?)(?=\n*###|$)"
    for number in issue_numbers:
        issue = g_repo.get_issue(number=int(number))
        title, shortdesc, format, schema, auth, desc = re.findall(pattern, issue.body, re.DOTALL)[0]
        folder_title = slugify(title)
        issues_info.append({'title': title, 'shortdesc': shortdesc, 'format': format, 'schema': schema, 'auth': auth, 'desc': desc, 'author': issue.user.login, 'folder_title': folder_title})

    # Create schema directories and files
    schemas_dir = os.path.join('repo', 'schemas')
    os.makedirs(schemas_dir, exist_ok=True)
    directory_entries = ""
    for info in issues_info:
        folder_path, schema_path, info_path = os.path.join(schemas_dir, info['folder_title']), os.path.join(schemas_dir, info['folder_title'], f'schema.{info["format"].lower()}'), os.path.join(schemas_dir, info['folder_title'], 'info.json')
        os.makedirs(folder_path, exist_ok=True)
        with open(schema_path, 'w') as f: f.write(info['schema'])
        with open(info_path, 'w') as f: json.dump(info, f, indent=4)
        directory_entries += new_readme_entry(info, info['schema'])

    # Update README
    readme_path = os.path.join('repo', '.github', 'README.md')
    updated_readme = update_readme(readme_path, directory_entries, len(issues_info))
    with open(readme_path, 'w') as f: f.write(updated_readme)

    # Git operations: commit and create PR
    repo.git.add(A=True)
    repo.index.commit('ci(schemas): Add new approved schemas')
    update_schemas_branch = Repo.create_head(repo, 'update-schemas', 'main')
    update_schemas_branch.checkout()
    repo.git.push('origin', 'update-schemas')
    pr_body = f"This pull request was automatically generated by the update-schemas action, and will add the following schemas to the repository:\n" + "\n".join([f'- {info["title"]}' for info in issues_info]) + "\n\nThis will close the following issues:\n" + "\n".join([f'- Closes #{num}' for num in issue_numbers])
    g_repo.create_pull(title='ci(schemas): Add new approved schemas', body=pr_body, base='main', head=update_schemas_branch.name)

if __name__ == '__main__': run()