name: Update Repo With New Schemas
on:
  workflow_dispatch
jobs:
  update-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get issues with 'schema-approved' label
        id: get_issues
        uses: actions/github-script@v5
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'schema-approved',
              state: 'open'
            });
            return issues.data.map(issue => issue.number).join(',');
      - name: Run the update-schemas action script
        uses: ./.github/actions/update-schemas
        with:
          repo_url: ${{ github.repository }}
          issue_list: ${{ steps.get_issues.outputs.result }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: update_schemas